name: UniquePlayer
main: hey.bengarrr.uniqueplayer.UniquePlayer
version: 0.0.5.0
author: Bengarrr
website: 
description: >

commands:
    UniquePlayerReload:
        description: This is a command to reload the configs in game.
        usage: /<command>
        permission: UniquePlayer.reload
        permission-message: You don't have <permission>
        aliases: [uniqueplayer]